services:
  server:
    container_name: server
    build:
      context: server
      dockerfile: Dockerfile.prod
    env_file:
      - env_files/prod/server.env
    secrets:
      - db_password
      - server_key
    ports:
      - "${SERVER_PORT}:8000"
    restart: unless-stopped
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - database-data:/var/lib/postgresql/data
    restart: unless-stopped

  caddy:
    container_name: caddy
    build:
      context: .
      dockerfile: caddy/Dockerfile
    env_file:
      - env_files/prod/server.env
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy-data:/data
    restart: unless-stopped

volumes:
  database-data:
  caddy-data:

secrets:
  db_password:
    environment: "DB_PASSWORD"
  server_key:
    environment: "SERVER_SECRET_KEY"