services:
  server:
    container_name: server-dev
    build:
      context: server
    env_file:
      - env_files/dev/server.env
    secrets:
      - db_password
    ports:
      - "${SERVER_PORT}:8000"
    volumes:
      - ./server/server:/server/server
    restart: unless-stopped
    depends_on:
      - database

  database:
    container_name: database-dev
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - database-dev-data:/var/lib/postgresql/data
    restart: unless-stopped

  client:
    container_name: client-dev
    build:
      context: client
    env_file:
      - env_files/dev/client.env
    ports:
      - "${CLIENT_PORT}:3000"
    volumes:
      - ./client/src:/client/src
      - ./client/public:/client/public
    restart: unless-stopped

volumes:
  database-dev-data:

secrets:
  db_password:
    environment: "DB_PASSWORD"
