services:
  server:
    container_name: server
    build:
      context: server
    env_file:
      - env_files/prod.env
    secrets:
      - db_password
    ports:
      - "${SERVER_PORT}:8000"
    restart: unless-stopped
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=${SERVER_DB_NAME}
      - POSTGRES_USER=${SERVER_DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - database-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  database-data:

secrets:
  db_password:
    environment: "DB_PASSWORD"