site_name: WINAK Docs
repo_url: https://github.com/Laurensdewachter/WINAK
theme:
  name: material
  palette:
    scheme: slate
    primary: custom
  features:
    - content.code.copy
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
